Prisma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('account.urls')),
    path('comment/',include('comment.urls')),
    # authentication views


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from comment import views
app_name = 'comment'

urlpatterns = [
      # add comment
      path('post-comment/<int:video_id>/', views.post_comment, name='post_comment'),
         # Added code to handle secondary replies
      path('post-comment/<int:video_id>/<int:parent_comment_id>/', views.post_comment, name='comment_reply'),
        # edit comment
       # delete comment
      path('<slug:slug>/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

core/urls.py
from django.urls import path,include
from core import views
from comment import views as comment_views

app_name = 'core'

urlpatterns = [
  path('', views.home, name="home"),
  path('search/', views.search, name='search_results'),
  path('create-content/', views.create_content, name="create_content"),
  path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
  path('video/<slug:video_slug>/', views.DetailView.as_view(), name="video_detail"),
  path('edit-content/<slug:video_slug>/<int:video_id>/', views.edit_content, name="edit_content"),
  path('<slug:video_slug>/<int:video_id>/delete/', views.delete_content, name="delete_content"),
  path('catagory-list/', views.catagory_list, name="catagory_list"),
  path('catagory/<catagory_name>/', views.catagory_detail, name="catagory_detail"),
  path('edit-comment/<int:video_id>/<int:comment_id>/', comment_views.edit_comment, name='edit_comment'),
]

comment/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from core.models import Video
from django.contrib.auth.models import User
# Create your models here.
class Comment(MPTTModel):
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name = 'comments')
    parent = TreeForeignKey('self',on_delete=models.SET_NULL,
                            null=True,
                            blank=True,
                            related_name='children')
    reply_to = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='replayers')
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    content = models.TextField()
    upvote = models.ManyToManyField(User, related_name="upvoter", default=None, blank=True)
    upvote_count = models.IntegerField(default='0')
    downvote =  models.ManyToManyField(User, related_name="downvoter", default=None, blank=True)
    downvote_count = models.IntegerField(default='0')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['created']

    def __str__(self):
        return  f'{self.content[:20]} by {self.user}'

comment/forms.py
from django import forms
from comment.models import Comment

class CommentForm(forms.ModelForm):
    content = forms.CharField(
                        widget=forms.Textarea(
                               attrs={
                               'class': 'form-group form-control',
                               'id': 'content',
                               'rows': 5,
                               'cols': 40
                               }
                        )
                      )
    class Meta:
        model = Comment
        fields = ('content',)

class CommentUpdateForm(forms.ModelForm):
    content = forms.CharField(
                        widget=forms.Textarea(
                               attrs={
                               'class': 'form-group form-control',
                               'id':'content',
                               'rows': 3,
                               'cols': 10,
                               }
                        )
                      )
    class Meta:
        model = Comment
        fields = ('content','status',)

comment/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from .forms import CommentForm,CommentUpdateForm
from core.models import Video
from .models import Comment
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required
@csrf_exempt
def  post_comment( request , video_id , parent_comment_id = None ):
    video  =  get_object_or_404(Video,id=video_id )
    print('this is post_slug')
    # Processing POST request
    if  request.method == 'POST' :
        comment_form  =  CommentForm(request.POST)
        if  comment_form.is_valid ():
            new_comment  =  comment_form.save(commit = False )
            new_comment.video =  video
            new_comment.user =  request.user
            video_slug = video.slug
            print(new_comment.user)
            child = bool

            # Secondary reply
            if  parent_comment_id:
                parent_comment  =  Comment.objects.get(id=parent_comment_id)
                # If the reply level exceeds the second level, it will be converted to the second level
                new_comment.parent_id = parent_comment.get_root().id

                # Respondent
                new_comment.reply_to = parent_comment.user
                new_comment.save()
                print(new_comment)
                # super_parent = Comment.objects.get(id = parent_comment.get_root().id)
                # print(super_parent.get_children().count())
                # if super_parent.get_children().count() > 1:
                #     child = True
                return HttpResponse("200 OK")
            new_comment.save()
            return redirect('core:video_detail',video_slug=video_slug)
        else :
            return HttpResponse( "The content of the form is incorrect, please fill in again.")
    # Processing GET request
    elif request.method  ==  'GET':
        comment_form  =  CommentForm()
        context  = {
            'comment_form' : comment_form ,
            'video_id' : video_id ,
            'parent_comment_id' : parent_comment_id
        }
        return  render(request, 'comment/reply.html', context)
    # Processing other requests
    else :
        return  HttpResponse( "Only accept GET/POST requests.")

@login_required
@csrf_exempt
def edit_comment(request, video_id, comment_id):
    # video  =  get_object_or_404 (Video, id=video_id)
    comment = Comment.objects.get(id=comment_id)
    print(comment)
    if request.method == 'POST':
        edit_form = CommentUpdateForm(request.POST,instance=comment)
        print(edit_form)
        if edit_form.is_valid():
            edit_form.status = False
            edit_form.save()
            messages.success(request, f'Your comment has been updated!')
            return HttpResponse('Updating...')
            # return redirect('post_detail',slug=post.slug)
        else:
            return HttpResponse("The content of the form is incorrect, please fill in again.")
    else:
        edit_form = CommentUpdateForm(instance=comment)
        print(edit_form)
    context = {
    'edit_form': edit_form,
    'video_id' : video_id,
    'comment_id': comment_id,
    }
    return render(request,'comment/edit_comment.html',context=context)

@login_required
def delete_comment(request, slug, comment_id):
    video = get_object_or_404(Video,slug=slug)
    print(video)
    comment  = Comment.objects.get(id=comment_id).delete()
    messages.success(request, f'Your comment has been deleted!')
    return HttpResponseRedirect(reverse('core:video_detail',kwargs={'video_slug':slug}))

templates/comment/edit_comment.html
<!-- Load static file -->
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta  charset = "utf-8">
    <!-- <link  rel = "stylesheet"  href = "{% static 'bootstrap/css/bootstrap.min. css' %}" > -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <form action="{% url 'core:edit_comment' video_id comment_id %}" method="POST" id="edit_comment_form">
        <div class="form-group" >
          <!-- <label>Content</label> -->
          <!-- <textarea class="form-control" rows="5" cols="80" id="content" placeholder="">{{ form.content }}</textarea> -->
          {% csrf_token %}
          {{ edit_form.content }}
          <!-- <textarea class="form-control" rows="5" cols="80" id="content" placeholder="">{{ edit_comment_form }}</textarea> -->
        </div>
        <button type="submit" onclick = "confirm_submit({{ video_id }}, {{ comment_id }})"  class = "btn btn-primary">Update</button>
    </form>
    <!-- <button type="submit" class="btn btn-primary">Update</button> -->
    <!-- Submit button-->

     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


     <script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>


    <!-- csrf token -->
    <!-- <script  src = "{% static 'js/csrf.js' %}"></script> -->

    <script>

    function  confirm_submit(video_id, comment_id ){

        // call ajax to exchange data with the backend
        $.ajax ({
            url :  '/edit-comment/' + video_id + '/' + comment_id + '/',
            type :  'POST' ,
            data : { content: $('#content').val(), },
            // success callback
            success: function ( e ){
                if (e  ===  'Updating...'){
                    parent.location.reload();
                }
            }
        })
    }
    </script>

</body>
</html>

templates/comment/reply.html
<!-- Load static file -->
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta  charset = "utf-8">
    <!-- <link  rel = "stylesheet"  href = "{% static 'bootstrap/css/bootstrap.min. css' %}" > -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <form action = "." method = "POST" id = "reply_form">
        {% csrf_token %}
        <div  class = "form-group" >
          <!-- <label>Content</label> -->
          <textarea class="form-control" rows="5" cols="80" id="content" placeholder="">{{ form.content}}</textarea>

        </div>
    </form>
    <!-- Submit button-->
    <button  type="submit" onclick = "confirm_submit({{ video_id }}, {{ parent_comment_id }})"  class = "btn btn-primary">Send</button>

     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


      <!-- <script type="text/javascript" src="{% static "jquery/jquery-3.5.1.min.js" %}"></script> -->
      <script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>


    <!-- csrf token -->
    <!-- <script  src = "{% static 'js/csrf.js' %}"></script> -->

    <script>

    function  confirm_submit( video_id, comment_id ){

        // call ajax to exchange data with the backend
        $.ajax ({
            url :  '/comment/post-comment/' +  video_id + '/' + comment_id + '/',
            type :  'POST' ,
            data :  { content: $('#content').val(), },
            // success callback
            success: function ( e ){
                if (e  ===  '200 OK' ){
                    parent.location.reload();
                }
            }
        })
    }
    </script>

</body>
</html>