Prisma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('account.urls')),
    path('comment/',include('comment.urls')),
    # authentication views


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
     path('signup/', views.signup, name="signup"),
     # authentication
     path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
     path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
     path('profile/<int:profile_id>/', views.profile, name="profile"),
     path('update-profile/<int:profile_id>/', views.update_profile, name="update_profile"),
     # follow
     path('follow/', views.follow, name="follow"),
     # like
     path('like/', views.like, name="like"),
     # dislike
     path('dislike/', views.dislike, name="dislike"),
     # upvote comment
     path('upvote/', views.upvote, name="upvote"),
     # downvote comment
     path('downvote/', views.downvote, name="downvote"),
     # Add catagory to favourite
     path('add-favourite/<int:catagory_id>/', views.add_favourite, name="add_favourite"),
      # following_list
     path('following_list/', views.following_list, name="following_list"),

]

core/urls.py
from django.urls import path,include
from core import views
from comment import views as comment_views

app_name = 'core'

urlpatterns = [
  path('', views.home, name="home"),
  path('search/', views.search, name='search_results'),
  path('create-content/', views.create_content, name="create_content"),
  path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
  path('video/<slug:video_slug>/', views.DetailView.as_view(), name="video_detail"),
  path('edit-content/<slug:video_slug>/<int:video_id>/', views.edit_content, name="edit_content"),
  path('<slug:video_slug>/<int:video_id>/delete/', views.delete_content, name="delete_content"),
  path('catagory-list/', views.catagory_list, name="catagory_list"),
  path('catagory/<catagory_name>/', views.catagory_detail, name="catagory_detail"),
  path('edit-comment/<int:video_id>/<int:comment_id>/', comment_views.edit_comment, name='edit_comment'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
# 287/161
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from .validators import validate_file_extension

from django.utils.text import slugify

from moviepy.editor import *

from django.utils.encoding import python_2_unicode_compatible
from django.contrib.contenttypes.fields import GenericRelation

from hitcount.models import HitCountMixin
from hitcount.settings import MODEL_HITCOUNT


# Create your views here.
def convert(seconds):
    hours = seconds // 3600
    seconds %= 3600
    mins = seconds // 60
    seconds %= 60
    return hours, mins, seconds

class Catagory(models.Model):
    name = models.CharField(max_length=75)
    avatar = ProcessedImageField(default="default_category_avatar.jpg", upload_to='catagory_avatar/%Y/%m/%d/',
                                           null=True, blank=True,
                                           processors=[ResizeToFill(320, 180)],
                                           format='JPEG',
                                           options={'quality': 90})
    favourite = models.ManyToManyField(User, related_name="favourite", default=None, blank=True)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Video(models.Model, HitCountMixin):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="uploader")
    file = models.FileField(upload_to="videos/%Y/%m/%d/",validators=[validate_file_extension])
    thumbnail = ProcessedImageField(upload_to='video_thumbnail/%Y/%m/%d/',
                                           processors=[ResizeToFill(300, 180)],
                                           format='JPEG',
                                           options={'quality': 75})
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    catagory = models.ForeignKey(Catagory, on_delete=models.PROTECT, related_name='videos')
    like = models.ManyToManyField(User, related_name="like", default=None, blank=True)
    like_count = models.BigIntegerField(default='0')
    dislike = models.ManyToManyField(User, related_name="dislike", default=None, blank=True)
    dislike_count = models.BigIntegerField(default='0')
    hit_count_generic = GenericRelation(
        MODEL_HITCOUNT, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')


    class Meta:
        ordering = ['catagory']

    def __str__(self):
        return self.user.username +  " Catagory: " + self.catagory.name + " " +  self.title[:30]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        return super(Video, self).save(*args,**kwargs)

    @property
    def get_duration(self):
        video = VideoFileClip(self.file.path)
        video_duration = int(video.duration)
        hours, mins, secs = convert(video_duration)
        if secs < 10:
            secs = '0' + str(secs)
        if mins < 10:
            mins = '0' + str(mins)
        if hours != 0:
            duration = str(hours) + ":" + str(mins) + ":" + str(secs)
        else:
            duration = str(mins) + ":" + str(secs)
        return duration

core/forms.py
from django import forms
from core.models import Video



class ContentCreateForm(forms.ModelForm):
    title = forms.CharField(required=True,
                         widget=forms.TextInput(
                         attrs={
                         'class': 'form-control',
                         'placeholder': 'Write down your content title',
                         }))
    description = forms.CharField(required=True,
                                  widget=forms.Textarea(
                                  attrs={
                                  'class': 'form-control',
                                  'placeholder': 'Write down about your content',
                                  'rows': 5,
                                  'cols': 20,
                                  }))
    class Meta:
        model = Video
        fields = ('title','description','thumbnail','file','catagory')

        widgets = {
              'catagory': forms.Select(attrs={'class':'form-control'}),
        }

core/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from .models import Catagory,Video
from account.models import Profile,Follow
from django.contrib.auth.models import User
import subprocess
from PIL import Image
from moviepy.editor import *
# comments
from comment.models import Comment
from comment.forms import CommentForm

from core.forms import ContentCreateForm

from django.db.models import Q

from django.template.defaultfilters import slugify

from django.views.generic.edit import DeleteView

from hitcount.views import HitCountDetailView

from django.contrib.auth.decorators import login_required

from itertools import chain

from django.core.exceptions import PermissionDenied


# Create your views here.


def home(request):
    if request.user.is_authenticated:
        # video_list = []
        # cat_list = Catagory.objects.filter(favourite=request.user)
        # following_list = Follow.objects.filter(follower=request.user)
        # follower_videos = Video.objects.filter(user__in=following_list.values_list('following')).order_by('-hit_count_generic__hits')[0:5]
        # fav_cat_list = Video.objects.filter(catagory__in=cat_list.values_list('videos')).order_by('-hit_count_generic__hits')
        # popular_list = Video.objects.exclude(title__in=fav_cat_list.values_list('title')).order_by('-hit_count_generic__hits')
        # video_list = list(chain(follower_videos,fav_cat_list, popular_list))
        # video_list = list(dict.fromkeys(video_list))
        video_list = Video.objects.all().order_by('-hit_count_generic__hits')
        print(video_list)
    else:
        print(request.user)
        video_list = Video.objects.all().order_by('-hit_count_generic__hits')
    context = {
       'video_list': video_list,
    }
    return render(request,'core/home.html',context=context)

class DetailView(HitCountDetailView):
    model = Video        # your model goes here
    count_hit = True    # set to True if you want it to try and count the hit

    def get_object(self):
        video = Video.objects.get(slug=self.kwargs.get('video_slug'))
        return video

    def get_context_data(self, *args, **kwargs):
        context = super(DetailView, self).get_context_data(*args, **kwargs)
        video = self.get_object()
        print(video)
        catagory = video.catagory.id
        related_videos = Video.objects.filter(catagory=catagory).exclude(slug=video.slug)
        comments = video.comments.all()
        # comments = video.comments.filter(status=True)
        comment_form = CommentForm()
        user = User.objects.get(id=video.user.id)
        profile = get_object_or_404(Profile, user=user)
        if self.request.user.is_authenticated:
            following_list = Follow.objects.filter(follower=self.request.user)
            following_channel_list = following_list.values_list('following', flat=True)
        else:
            following_channel_list = None
        follower_count = user.follower.count()
        context['video'] = video
        context['comments'] = comments
        context['comment_form'] = comment_form
        context['follower_count'] = follower_count
        context['related_videos'] = related_videos
        context['profile'] = profile
        context['following_channel_list'] = following_channel_list
        return context




# def video_detail(request,video_slug, video_id):
#     video = get_object_or_404(Video, id=video_id)
#     catagory = video.catagory.id
#     related_videos = Video.objects.filter(catagory=catagory)
#     print(related_videos)
#     comments = video.comments.filter(status=True)
#     comment_form = CommentForm()
#     user = User.objects.get(id=video.user.id)
#     print(user)
#     follower_count = user.follower.count()
#     print(follower_count)
#     print(comment_form)
#     context = {
#     'video': video,
#     'comments': comments,
#     'comment_form': comment_form,
#     'follower_count': follower_count,
#     'related_videos': related_videos,
#     }
#     return render(request, 'core/video_detail.html',context)
@login_required
def search(request):
     query = request.GET.get('q')
     mark = bool
     videos = []
     following_channel_list = ''
     if query:
         profiles = Profile.objects.filter(
                                           Q(channel_name__iexact = query)|
                                           Q(channel_name__icontains = query))
         print(profiles)
         following_list = Follow.objects.filter(follower=request.user)
         print(following_list)
         search_videos = Video.objects.filter(
                                   Q(title__icontains = query) |
                                   Q(catagory__name__icontains = query) |
                                   Q(user__username__icontains = query)).order_by('like_count')
         # posts = list(dict.fromkeys(posts))
         # posts_count = len(posts)
         if profiles:
             following_channel_list = following_list.values_list('following', flat=True)
             print(following_channel_list)
     else:
         query = ""
         search_videos = None
         profiles = None
         following_channel_list = None
     context = {
       'query': query,
       'search_videos': search_videos,
       'profiles': profiles,
       'following_channel_list': following_channel_list,
       # 'posts_count': posts_count,
       'mark': mark,
     }
     return render(request, 'core/search_results.html', context=context)


def catagory_list(request):
    catagory_list = Catagory.objects.all().order_by('name')
    if request.user.is_authenticated:
        fav_cat_list = Catagory.objects.filter(favourite=request.user)
    else:
        fav_cat_list = None
    # fav_cat_list = fav_cat.values_list('favourite', flat=True)

    for catagory in catagory_list:
        videos = Video.objects.filter(catagory=catagory)
        videos_count = videos.count()
        catagory.videos_count = videos_count
        print(catagory)
        print(catagory.videos_count)

    context = {
    'catagory_list': catagory_list,
    'fav_cat_list': fav_cat_list,
    }
    return render(request,'core/catagory_list.html',context=context)

def catagory_detail(request,catagory_name):
    catagory = Catagory.objects.get(name=catagory_name)
    videos_list = Video.objects.filter(catagory=catagory)
    print(videos_list)
    context = {
     'catagory': catagory,
     'videos_list': videos_list,
    }
    return render(request,'core/catagory_detail.html',context=context)

@login_required
def create_content(request):
    if request.method == 'POST':
        form = ContentCreateForm(request.POST,request.FILES)
        if form.is_valid():
            video = form.save(commit=False)
            video.user = request.user
            # video_title = video.cleaned_data.get('title')
            # slug = slugify(video_title)
            video.save()
            return redirect('core:video_detail',video_slug=video.slug)
    else:
        form = ContentCreateForm()
    context = {
    'form': form,
    }
    return render(request,'core/content_create_form.html',context=context)

@login_required
def edit_content(request,video_slug,video_id):
    video = Video.objects.get(id=video_id)
    edit_content_page = True
    if request.user == video.user:
        if request.method == 'POST':
            form = ContentCreateForm(request.POST,request.FILES,instance=video)
            if form.is_valid():
                form.save()
                return redirect('core:video_detail',video_slug=video.slug)
        else:
            form = ContentCreateForm(instance=video)
    else:
        raise PermissionDenied()
    context = {
        'form': form,
        'edit_content_page': edit_content_page,
    }
    return render(request,'core/content_create_form.html',context=context)

@login_required
def delete_content(request, video_slug, video_id):
    video  = get_object_or_404(Video,id=video_id)
    profile = get_object_or_404(Profile,user=video.user)
    if request.user == video.user:
        if request.method == 'POST':
            video.delete()
            return redirect('account:profile', profile_id=profile.id)
    else:
        raise PermissionDenied()
    context = {
     'video': video,
    }
    return render(request,'core/video_confirm_delete.html', context=context)

templates/core/catagory_detail.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}
{% block title %} {{ catagory }} . Prisma {% endblock %}
{% block css %}
{% endblock %}

{% block content %}

<h4 class="text-center my-4">{{ catagory }}<hr class="content text-center"></h4>

<div class="container-fluid py-5">
    <div class="row px-3">
      {% for video in videos_list %}
        <div class="col-3">
          <a href="{% url 'core:video_detail' video_slug=video.slug %}">
            <div class="image">
              <img src="{{ video.thumbnail.url }}" alt="" width="300" height="163">
              <div class="bottom-right bg-dark text-light mr-2 px-1">{{ video.get_duration }}</div>
              <div class="centered"><i class="fas fa-play fa-2x"></i></div>
            </div>
          </a>

          <div class="row d-flex align-self-center mt-2">
            <a href="{% url 'account:profile' profile_id=video.user.user_profile.id %}">
            <div class="col-2">
              <img src="{{ video.user.user_profile.profile_pic.url }}" class="rounded-circle" alt="" width="35" height="35">
            </div>
           </a>
            <div class="col-9 pl-1">
              <a href="{% url 'core:video_detail' video_slug=video.slug %}">
                <p class="mb-0">{{ video.title }}</p>
              </a>
              <p class="text-monotspace my-1">
                <a href="{% url 'account:profile' profile_id=video.user.user_profile.id %}">
                  <small style="font-size:14px">{{ video.user.user_profile.channel_name }}</small>
                </a>
              </p>
              <a href="{% url 'core:video_detail' video_slug=video.slug %}">
                <p class="text-monospace text-muted">{% get_hit_count for video %} Views<span class="float-right">{{ video.created|date:"M d,Y" }}</span></p>
              </a>
            </div>
          </div>
        </div>

      {% endfor %}

   </div>
</div>


{% endblock %}

templates/core/catagory_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Catagory List {% endblock %}
{% block css %}
{% endblock %}

{% block content %}
<div class="container-fluid py-5">
    <div class="row px-3">
      {% if messages %}
      {% for message in messages %}
       <div class="col-10 alert alert-{{ message.tags }} text-center mx-auto">
        {{ message}}
      </div>
        {% endfor %}
        {% endif %}

      {% for catagory in catagory_list %}
        <div class="col-3">
            <div class="image">
              <a href="{% url 'core:catagory_detail' catagory_name=catagory.name %}">
               <img src="{{ catagory.avatar.url }}" alt="" width="300" height="163">
                <div class="centered font-weight-bold">{{ catagory.name }}</div>
              </a>
            </div>

          <div class="row mt-2">
            <div class="col-12">
              <a href="{% url 'core:catagory_detail' catagory_name=catagory.name %}">
                <p class="mb-0 text-center font-weight-bold">{{ catagory.name }}</p>
              </a>
              <p class="text-monospace ml-2 mr-3">
                <a href="{% url 'core:catagory_detail' catagory_name=catagory.name %}">
                  <span class="">{{ catagory.videos_count}} Video{{ catagory.videos_count|pluralize}}</span>
                </a>
                {% if catagory in fav_cat_list %}
                <span class="float-right">{{ catagory.favourite.count }}
                  <a href="{% url 'account:add_favourite' catagory_id=catagory.id %}">
                    <i id="favourite" class="icon-heart fas fa-heart icon-c"></i>
                  </a>
                </span>
                {% else %}
                <span class="float-right">{{ catagory.favourite.count }}
                  <a href="{% url 'account:add_favourite' catagory_id=catagory.id %}">
                    <i class="icon-heart fas fa-heart icon-a"></i>
                  </a>
                </span>
                {% endif %}
              </p>
            </div>
          </div>
        </div>

      {% endfor %}

   </div>
</div>
<script>
// like video
$(document).on('click', '#like-button', function (e) {
  e.preventDefault();
  $.ajax({
    type: 'POST',
    url: '{% url "account:like" %}',
    data: {
      videoid: $('#like-button').val(),
      csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
      action: 'post'
    },
    success: function (json) {
      document.getElementById("like_count").innerHTML = json['result']
    },
    error: function (xhr, errmsg, err) {

    }
  });
})

</script>
{% endblock %}

templates/core/home.html
{% extends 'base.html' %}
{% load static %}
{% load hitcount_tags %}
{% block css %}
{% endblock %}

{% block content %}

  <div class="container-fluid py-5">
      <div class="row px-3">
        {% for video in video_list %}
          <div class="col-sm-4 col-xl-3">
            <a href="{% url 'core:video_detail' video_slug=video.slug %}">
              <div class="image">
                <img src="{{ video.thumbnail.url }}" class="img-responsive" alt="" width="300" height="163">
                <div class="bottom-right bg-dark text-light mr-2 px-1">{{ video.get_duration }}</div>
                <div class="centered"><i class="fas fa-play fa-2x"></i></div>
              </div>
            </a>

            <div class="row d-flex align-self-center mt-2">
              <div class="col-2">
                <a href="{% url 'account:profile' profile_id=video.user.user_profile.id %}">
                  <img src="{{ video.user.user_profile.profile_pic.url }}" class="rounded-circle" alt="" width="35" height="35">
                </a>
              </div>
              <div class="col-9 pl-1">
                <a href="{% url 'core:video_detail' video_slug=video.slug %}">
                  <p class="mb-0">{{ video.title }}</p>
                </a>
                <p class="text-monospace my-1">
                  <a href="{% url 'account:profile' profile_id=video.user.user_profile.id %}" style="font-size:14px">{{ video.user.user_profile.channel_name }}</a>
                    <i class="fas fa-thumbs-up float-right"> {{ video.like_count}}</i>
                </p>
                <p class="text-monospace text-muted">{% get_hit_count for video %} views<span class="float-right">{{ video.created|date:"M d,Y" }}</span></p>
              </div>
            </div>
          </div>

        {% endfor %}

     </div>
  </div>



<!-- <img src="{{ video.thumbnail.url}}" alt="" width="287" height="163">

<video width='400' controls>
<source src="{{ video.file.url }}">
Your browser does not support the video tag.
</video>
<br><br> -->

{% endblock content %}

templates/core/search_results.html
{% extends 'base.html' %}
{% load static %}
{% load date_filter %}
{% load hitcount_tags %}
{% block title %}Search . Result{% endblock %}
{% block css %}
{% endblock %}

{% block content %}

<div class="container">
  {% if query %}
          {% if profiles or search_videos %}
            <h5 class="text-center my-4">Search Results for <span class="text-success">"{{ query }}"</span> <hr class="search text-center"></h5>
            <div class="row">
              <div class="col-md-9 mx-auto">
                    <!-- start of profiles -->
                    {% if profiles %}
                      {% for profile in profiles %}
                        <div class="row my-3">
                          <div class="col-4 text-center">
                            <a href="{% url 'account:profile' profile_id=profile.id %}">
                             <img src="{{ profile.profile_pic.url }}" alt="" width="136" height="136" class="rounded-circle">
                            </a>
                          </div>
                          <div class="col-6 py-2 pl-0">
                            <a href="{% url 'account:profile' profile_id=profile.id %}">
                              <p class="mb-0" style="font-size:20px;">{{ profile.channel_name }}</p>
                                <small class="text-secondary">
                                  <span id="follower_count_{{profile.user_id}}">
                                  {{ profile.user.follower.count }} follower{{ profile.user.follower.count|pluralize }}
                                  </span>
                                  . {{ profile.total_videos }} video{{ profile.total_videos|pluralize }} <br>
                                  {{ profile.description|truncatechars:120 }}
                                </small>
                             </a>
                          </div>
                          <div class="col-2 py-5">
                            <a href="{% url 'account:profile' profile_id=profile.id %}">
                              {% if not profile.user == request.user %}
                                 {% if following_channel_list %}
                                    {% if profile.user.id in following_channel_list %}
                                     <button class="btn btn-info btn-sm mr-2" id="follow-button" data-followid="{{profile.user.id}}" value="{{ profile.user.id }}">
                                        <span id="follow_{{profile.user.id}}">Following</span>
                                     </button>
                                     {% else %}
                                     <button class="btn btn-info btn-sm mr-2" id="follow-button" data-followid="{{profile.user.id}}" value="{{ profile.user.id }}">
                                       <span id="follow_{{profile.user.id}}">Follow</span>
                                     </button>
                                    {% endif %}
                                 {% else %}
                                    <button class="btn btn-info btn-sm mr-2" id="follow-button" data-followid="{{profile.user.id}}" value="{{ profile.user.id }}">
                                      <span id="follow_{{profile.user.id}}">Follow</span>
                                    </button>
                                 {% endif %}
                             {% endif %}
                           </a>
                          </div>
                        </div>
                    {% endfor %}
                   {% endif %}
                   <!-- end of profile  -->

                   <!-- start of profile videos -->
                     {% if profiles %}
                       {% for profile in profiles %}
                         {% if profile.videos %}
                           {% for video in profile.videos %}
                             <div class="row mb-3">
                               <div class="col-4 image">
                                 <a href="{% url 'core:video_detail' video_slug=video.slug %}">
                                   <img src="{{ video.thumbnail.url }}" alt="" width="246" height="138" class="">
                                   <div class="search-bottom-right bg-dark text-light mr-4 px-1">{{ video.get_duration }}</div>
                                   <div class="centered"><i class="fas fa-play fa-2x"></i></div>
                                </a>
                               </div>
                               <div class="col-8 py-2 pl-0">
                                 <a href="{% url 'core:video_detail' video_slug=video.slug %}">
                                   <p class="mb-0" style="font-size:20px;">{{ video.title }}</p>
                                   </a>
                                   <small class="text-secondary">
                                     <a href="{% url 'account:profile' profile_id=video.user.user_profile.id %}" class="text-muted">
                                       {{ video.user.user_profile.channel_name }}</a>.
                                       <a href="{% url 'core:video_detail' video_slug=video.slug %}">{% get_hit_count for video %} views . {{ video.updated|timesince|upto:',' }} ago</a>
                                   </small><br>
                                   <a href="{% url 'core:video_detail' video_slug=video.slug %}">
                                     <small class="text-secondary">
                                       {{ video.description|truncatechars:120 }}
                                     </small>
                                   </a>
                               </div>

                             </div>
                       {% endfor %}
                      {% endif %}
                    {% endfor %}
                  {% endif %}
                  <!-- end of videos  -->

                   <!-- start of profile videos -->
                   {% if search_videos %}
                     {% for video in search_videos %}
                         <div class="row mb-3">
                             <div class="col-4 image">
                               <a href="{% url 'core:video_detail' video_slug=video.slug %}">
                                 <img src="{{ video.thumbnail.url }}" alt="" width="246" height="138" class="">
                                 <div class="search-bottom-right bg-dark text-light mr-4 px-1">{{ video.get_duration }}</div>
                                 <div class="centered"><i class="fas fa-play fa-2x"></i></div>
                              </a>
                             </div>
                             <div class="col-8 py-2 pl-0">
                               <p class="mb-0" style="font-size:20px;">{{ video.title }}</p>
                                 <small class="text-secondary">
                                   <a href="{% url 'account:profile' profile_id=video.user.user_profile.id %}">{{ video.user.user_profile.channel_name }} </a>. {% get_hit_count for video %} views . {{ video.updated|timesince|upto:',' }} ago
                                 </small><br>
                                 <small class="text-secondary">
                                   {{ video.description|truncatechars:120 }}
                                 </small>
                             </div>
                         </div>
                    {% endfor %}
                  {% endif %}
                  <!-- end of videos  -->

             </div>
            </div>
          {% else %}
            <div class="row align-items-center" style="height:550px">
              <div class="col">
                <h5 class="text-center my-4">No Result Found For <span class="text-danger">"{{ query }}"</span></h5>
              </div>
            </div>
         {% endif %}

  {% endif %}

</div>
<script>
// Follow/UnFollow
$(document).on('click', '#follow-button', function (e) {
  e.preventDefault();
  // var video_user =  document.getElementById('follow-button').value;
  var video_user = $(this).attr("data-followid");
  console.log(video_user);
  var follow = 'follow_' + video_user;
  console.log(follow);
  // console.log("upvote_count:" + upvote_count);
  var selector = $(this);
  $.ajax({
    type: 'POST',
    url: '{% url "account:follow" %}',
    data: {
      // video_user: $('#follow-button').val(),
      video_user: $(this).attr("data-followid"),
      // csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
      action: 'post'
    },
    // $('input[name=csrfmiddlewaretoken]').val(),
    success: function (json) {
        console.log(json);
        if (json['result'] < 2)
        {
          document.getElementById("follower_count_" + video_user).innerHTML = json['result'] + ' follower ';
        }
        else{
          document.getElementById("follower_count_" + video_user).innerHTML = json['result'] + ' followers ';
        }
      if(document.getElementById(follow).innerHTML != 'Following'){
        document.getElementById(follow).innerHTML = 'Following';
      }
      else{
        document.getElementById(follow).innerHTML = 'Follow';
      }
    },
    error: function (xhr, errmsg, err) {

    }
  });
})
</script>

{% endblock %}