Prisma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('account.urls')),
    path('comment/',include('comment.urls')),
    # authentication views


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
     path('signup/', views.signup, name="signup"),
     # authentication
     path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
     path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
     path('profile/<int:profile_id>/', views.profile, name="profile"),
     path('update-profile/<int:profile_id>/', views.update_profile, name="update_profile"),
     # follow
     path('follow/', views.follow, name="follow"),
     # like
     path('like/', views.like, name="like"),
     # dislike
     path('dislike/', views.dislike, name="dislike"),
     # upvote comment
     path('upvote/', views.upvote, name="upvote"),
     # downvote comment
     path('downvote/', views.downvote, name="downvote"),
     # Add catagory to favourite
     path('add-favourite/<int:catagory_id>/', views.add_favourite, name="add_favourite"),
      # following_list
     path('following_list/', views.following_list, name="following_list"),

]

core/urls.py
from django.urls import path,include
from core import views
from comment import views as comment_views

app_name = 'core'

urlpatterns = [
  path('', views.home, name="home"),
  path('search/', views.search, name='search_results'),
  path('create-content/', views.create_content, name="create_content"),
  path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
  path('video/<slug:video_slug>/', views.DetailView.as_view(), name="video_detail"),
  path('edit-content/<slug:video_slug>/<int:video_id>/', views.edit_content, name="edit_content"),
  path('<slug:video_slug>/<int:video_id>/delete/', views.delete_content, name="delete_content"),
  path('catagory-list/', views.catagory_list, name="catagory_list"),
  path('catagory/<catagory_name>/', views.catagory_detail, name="catagory_detail"),
  path('edit-comment/<int:video_id>/<int:comment_id>/', comment_views.edit_comment, name='edit_comment'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/a858a25b98.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

    <title>{% block title %} Prisma {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block css %}
    {% endblock %}

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mx-auto">
       <a class="navbar-brand" href="{% url 'core:home' %}">Prisma</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>

       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item mx-3">
             <a class="nav-link" href="{% url 'core:catagory_list' %}">Categories</a>
           </li>

           <!-- <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Categories
             </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

               <a class="dropdown-item" href="">News</a>

             </div>

           </li> -->

           <li class="nav-item mx-3">
             <a class="nav-link" href="{% url 'core:create_content' %}">Create</a>
           </li>
         </ul>

         {% if user.is_authenticated %}
         <div class="nav-item dropdown">
           <a class="nav-link dropdown" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <img src="{{ request.user.user_profile.profile_pic.url }}" width="40" height="40" class="rounded-circle">
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="dropdown-item" href="{% url 'account:profile' profile_id=request.user.user_profile.id %}">My Channel</a>
             <a class="dropdown-item" href="{% url 'account:update_profile' profile_id=request.user.user_profile.id %}">Edit Profile</a>
             <a class="dropdown-item" href="{% url 'account:following_list' %}">Following</a>
             <a class="dropdown-item" href="{% url 'core:create_content' %}">Create Content</a>
             <a class="dropdown-item" href="{% url 'account:logout' %}">Log Out</a>
           </div>
         </div>
        {% endif %}
        <form class="form-inline my-2 my-lg-0 mx-3" action = '{% url 'core:search_results' %}' method="GET">
          <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search" required>
          <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
        </form>
         <!-- <form class="form-inline my-2 my-lg-0 mx-3" action = '{% url 'core:search_results' %}' method="GET">
           <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search" required>
           <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->

        <div class="nav-item">
          {% if request.user.is_authenticated %}
            <a href="{% url 'account:logout' %}" class="btn btn-outline-primary">Logout</a>
          {% else %}
            <a href="{% url 'account:login' %}" class="btn btn-outline-primary">LogIn</a>
            <a href="{% url 'account:signup' %}" class="btn btn-outline-success">Register</a>
          {% endif %}
         </div>


       </div>
   </nav>

    <!-- <div class="container-fluid py-3"> -->
      {% block content %}
      {% endblock %}
    <!-- </div> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>